### ISSUE TITLE
Split Up derivedTupleVariables.h

### ISSUE THREAD

**Issue by caleb-james-smith** [susy2015/ZInvisible#160]
Split derivedTupleVariables.h into multiple files.
- define one class per header file
- include new header files where needed
- consider making a folder for these files

**Comment by cmshcal12** [comment]
derivedTupleVariables.h is a bit smaller now
https://github.com/susy2015/ZInvisible/blob/organizeClasses/Tools/derivedTupleVariables.h

**Comment by caleb-james-smith** [comment]
Thanks for your input @cmshcal12 .

**Comment by nstrobbe** [comment]
Why is cmshcal12 doing a SUSY analysis? (S)he is supposed to be calibrating QIE cards!

**Comment by caleb-james-smith** [comment]
Well... this was an accident. I was logged in as cmshcal12 to accept a collaboration invitation from Mark. Then I went to make a comment here... and this is the result. I did the same thing recently when Grace was logged into GitHub on cmsnghcal01.

**Comment by nstrobbe** [comment]
haha 😆

**Comment by caleb-james-smith** [comment]
Joe commented, "I also suggest to move ALL include files into the include folder, then remove the "include/" from every line of this file. Then there is a place in the makefiles where you can set the include file locations."

**Comment by caleb-james-smith** [comment]
I have implemented your suggestion @pastika . Here is the pull request.

https://github.com/susy2015/ZInvisible/pull/164
