### ISSUE TITLE
MakePlots takes lumi from AnaSamples::luminosity_YEAR, ignores "-L" flag to set lumi

### ISSUE THREAD

**Issue by jsw-fnal** [susy2015/ZInvisible#202]
The luminosity is currently stored in two places: AnaSamples::luminosity_YEAR and in the StopCfg files.  MakePlots currently takes the luminosity from AnaSamples.  MakePlots has a flag, "-L" to set the luminosity at run time, but that flag is ignored in favor of the AnaSamples luminosity.

It would be better to keep the luminosity only in one place, the StopCfg files, and have all code take the luminosity from there.  This can be done if the "-L" flag is not ignored.  When using condorSubmit.py, makePlots is called with the "-L" flag, and the luminosity is taken from the StopCfg files provided you use the "-r" reference luminosity flag.

**Comment by jsw-fnal** [comment]
#201 contains code that handles this properly.  Unfortunately, that branch has diverged considerably from master, so some work will be necessary to extract only the relevant changes.

**Comment by caleb-james-smith** [comment]
Hi @jsw-fnal . When you use the "-r" flag for condorSubmit.py, do you have to pass a string or a luminosity?

**Comment by caleb-james-smith** [comment]
Ok, now that the PR is merged I will close the issue.
