### ISSUE TITLE
Improve systematics handling to better match log-normal nuisance parameters

### ISSUE THREAD

**Issue by jsw-fnal** [susy2015/ZInvisible#270]
https://github.com/susy2015/ZInvisible/blob/f2e783d2ab846aa9beae6c70263b647032d9ea0d/Tools/python/Run_modules.py#L437-L472

**Comment by jsw-fnal** [comment]
All of our nuisance parameters are log-normal distributed.  Suppose your nuisance parameter is a random variable X ~ log-normal.  Then, ln(X) ~ normal.  So, we can treat the *log* of all our systematics as though it is normal-distributed.

If C is the "central value", U is the "one sigma up yield", and D is the "one sigma down yield", then usually we would take (U - C) and (D - C) as the upward and downward systematic, respectively.  But now we need to use [log(U) - log(C)] and [log(D) - log(C)] instead.  This has implications for getting the total systematic uncertainty.  Notice that log(U) - log(C) = log(U/C) and log(D) - log(C) = log(D/C).

To get the total uncertainty, we would usually sum (U-C)² and (D-C)² and take the square root (AKA sum-in-quadrature).  Now we need to sum the square of the log of the ratios, then take the square root and exponentiate it instead.  So our total upward uncertainty is exp{√[log²(U1/C) + log²(U2/C) + ...]}, and similarly for the total downward uncertainty.

One thing to be careful of in calculating the total upward and downward uncertainties is that we should sum the uncertainties that actually increase the yield to get the total upward uncertainty, and similarly sum the uncertainties that actually decrease the yield to get the total downward uncertainty.

The log-normal distribution also has implications for symmetrizing uncertainties in the case that both the up and down variations lie on the same side of the central value.  Usually, we would symmetrize normal-distribution systematics by shifting both U and D so that their average is equal to C.  That is, U' = U + C - (U+D)/2 and D' = D + C - (U+D)/2.  But with log-normal systematics, we want to shift log(U) and log(D) so that their average is equal to log(C).  Then log(U') = log(U) + log(C) + (log(U) + log(D))/2 and similarly for log(D').  With a bit of algebra, we can convert this to log(U'/C) = log(U/√(U*D)).  That is, we divide each ratio U/C or D/C by the geometric mean of the ratios √(U/C * D/C) to get the symmetrized systematic ratio in each direction.

**Comment by jsw-fnal** [comment]
This is implemented in #271

**Comment by caleb-james-smith** [comment]
Changes moved to PR https://github.com/susy2015/ZInvisible/pull/274
